<a href="https://colab.research.google.com/github/Vignesh424/Heart_Pred/blob/main/Heart_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
#import the packages
import numpy as np
import pandas as pd

In [15]:
#Read the file
data = pd.read_csv('/content/heart.csv')

In [16]:
#Info of the data
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Age             918 non-null    int64  
 1   Sex             918 non-null    object 
 2   ChestPainType   918 non-null    object 
 3   RestingBP       918 non-null    int64  
 4   Cholesterol     918 non-null    int64  
 5   FastingBS       918 non-null    int64  
 6   RestingECG      918 non-null    object 
 7   MaxHR           918 non-null    int64  
 8   ExerciseAngina  918 non-null    object 
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object 
 11  HeartDisease    918 non-null    int64  
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB


In [17]:
#Shape of the data
data.shape

(918, 12)

In [18]:
#Print First 5 Rows of Data
data.head()

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140          289          0     Normal    172   
1   49   F           NAP        160          180          0     Normal    156   
2   37   M           ATA        130          283          0         ST     98   
3   48   F           ASY        138          214          0     Normal    108   
4   54   M           NAP        150          195          0     Normal    122   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              N      0.0       Up             0  
1              N      1.0     Flat             1  
2              N      0.0       Up             0  
3              Y      1.5     Flat             1  
4              N      0.0       Up             0

In [19]:
X = data.iloc[:,[0,1,2,3,4,5,6,7,8,9,10]].values
Y = data.iloc[:,[11]].values

In [20]:
#Machine understands Numbers, So we need to use LabelEncoder
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
X[:,1] = le1.fit_transform(X[:,1])
le2 = LabelEncoder()
X[:,2] = le2.fit_transform(X[:,2])
le3 = LabelEncoder()
X[:,6] = le3.fit_transform(X[:,6])
le4 = LabelEncoder()
X[:,8] = le4.fit_transform(X[:,8])
le5 = LabelEncoder()
X[:,10] = le5.fit_transform(X[:,10])

In [21]:
print(X)

[[40 1 1 ... 0 0.0 2]
 [49 0 2 ... 0 1.0 1]
 [37 1 1 ... 0 0.0 2]
 ...
 [57 1 0 ... 1 1.2 1]
 [57 0 1 ... 0 0.0 1]
 [38 1 2 ... 0 0.0 2]]


### **Splitting Dataset into Training set and Test set**

In [22]:
from sklearn.model_selection import train_test_split
(X_train,X_test,Y_train,Y_test) = train_test_split(X,Y,test_size=0.2,random_state=0)

## **Training Model**

In [23]:
from sklearn.ensemble import RandomForestClassifier
regression = RandomForestClassifier(random_state=0)
regression.fit(X,Y)

<ipython-input-23-8f53b238dcaa>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  regression.fit(X,Y)


RandomForestClassifier(random_state=0)

## **Testing Result**

In [24]:
#Predict
Y_pred = regression.predict(X_test)

In [25]:
from sklearn.metrics import classification_report, confusion_matrix
print('Confusion_Matrix\n',confusion_matrix(Y_test, Y_pred))
print()
print()
print('Classification Report\n',classification_report(Y_test, Y_pred))
     

Confusion_Matrix
 [[ 77   0]
 [  0 107]]


Classification Report
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        77
           1       1.00      1.00      1.00       107

    accuracy                           1.00       184
   macro avg       1.00      1.00      1.00       184
weighted avg       1.00      1.00      1.00       184

